export const SITE_TITLE = 'Imobiliária Rio Branco'
export const SITE_URL = 'https://sbfb5vmxug.map.azionedge.net'
export const ASSETS_URL = 'https://sbfb5vmxug.map.azionedge.net'
export const API_URL = 'https://o2u4kwbklg.map.azionedge.net'
export const FACEBOOK_URL = 'https://www.facebook.com/imobiliariariobranco/'
export const YOUTUBE_URL = 'https://www.youtube.com/user/imoRioBranco'
export const INSTAGRAM_URL = 'https://www.instagram.com/imobiliariariobranco/'
export const WHATSAPP_URL = 'https://api.whatsapp.com/send?phone=5518996041075&text='
export const PHONE_NUMBER = 'tel:182104 6944'
